require:
  - rubocop-rake # * Rake-specific analysis. (Official)
  - rubocop-rspec # * RSpec-specific analysis. (Official)

AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: true
  NewCops: 'enable'

Layout/LineLength:
  Enabled: true
  Max: 250

Metrics/AbcSize:
  Enabled: false # * Keeping these off due to complexity of refactoring existing code

Metrics/BlockLength:
  Enabled: true
  CountAsOne: ["array", "heredoc", "method_call"]
  AllowedMethods: ["included"]
  Max: 50

Metrics/MethodLength:
  Enabled: true
  CountAsOne: ["array", "heredoc", "method_call"]
  Max: 50

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: 'compact'
